### ISSUE TITLE
Why m3u8 link of removed?

### ISSUE THREAD

**Issue by HiddenPirates** [TechShreyash/AnimeDex#17]
Bro why you have removed m3u8 option?
If this is not working then how this project (https://github.com/riimuru/gogoanime-api) can grab m3u8 link?

**Comment by TechShreyash** [comment]
@HiddenPirates The scrapper animedex was using isn't working, had to fix that


As for https://github.com/riimuru/gogoanime-api

My scrapper and this project's scrapper are different 

Mine stopped working for some unknown reasons and i ain't getting time to fix that
