### ISSUE TITLE
How to remove ads. Bro 

### ISSUE THREAD

**Issue by gusfing** [TechShreyash/AnimeDex#20]

**Comment by TechShreyash** [comment]
@gusfing use any ad blocker

or brave browser

**Comment by gusfing** [comment]
I'm thinking to use this as live site so how I can remove other sources and only use gogo and Zoro

**Comment by TechShreyash** [comment]
@gusfing didnt understand what u r trying to say

**Comment by TechShreyash** [comment]
Use server 1 and 2 to watch animes without ads
