### ISSUE TITLE
Internal Server Error.

### ISSUE THREAD

**Issue by OrdinaryEnder** [TechShreyash/AnimeDex#28]
**Describe the bug**
```py
Traceback (most recent call last):
  File "/var/task/app.py", line 150, in get_episode
    data = TechZApi.gogo_episode(f"{anime}-episode-{episode}")
  File "/var/task/utils/techzapi.py", line 65, in gogo_episode
    data = requests.get(
  File "/var/task/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**To Reproduce**
Trying to watch Dragon Ball Super: Super Hero

**Expected behavior**
Watch the anime

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Android 11]
 - Browser [Chrome]
 - Version [ 114.0.5735.60]

**Smartphone (please complete the following information):**
 - Device: [Vivo Y12s]
 - OS: [Android 11]
 - Browser [Chrome]
 - Version [ 114.0.5735.60]

**Additional context**

**Comment by TechShreyash** [comment]
send url of the episode

**Comment by OrdinaryEnder** [comment]
> send url of the episode

https://animedex.ordinaryender.my.eu.org/anime/super-dragon-ball-heroes-ultra-god-mission

**Comment by TechShreyash** [comment]
![Screenshot_20230617-214119_Chrome](https://github.com/TechShreyash/AnimeDex/assets/82265247/6dddf40b-6f8b-4823-aec4-da09523d2ea4)

It is working ...
